leftnav:
- identifier: 04926453-2a3f-f348-fbfa-2399ff7c1348
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-363b86b1a38c4f87aaa8a86ab9f017de
  name: Online Publication
  url: http://introtodeeplearning.com/2020/index.html
  weight: 1000
